# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Coinset < Formula
  desc "CLI for accessing the Chia blockchain."
  homepage "https://www.coinset.org/"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/coinset-org/cli/releases/download/v1.0.1/coinset_Darwin_arm64.tar.gz"
      sha256 "134297880286e18fbbe1d31ed00fd44d26975cc70a3e8c44707fa21135d54d37"

      def install
        bin.install "coinset" => "coinset"
        output = Utils.popen_read("SHELL=bash #{bin}/coinset completion bash")
        (bash_completion/"coinset").write output
        output = Utils.popen_read("SHELL=zsh #{bin}/coinset completion zsh")
        (zsh_completion/"_coinset").write output
        prefix.install_metafiles
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/coinset-org/cli/releases/download/v1.0.1/coinset_Darwin_x86_64.tar.gz"
      sha256 "0bbc6ab7dd236e2457b63a48f6da8a84768c3204d10801cc86870da4adb07f12"

      def install
        bin.install "coinset" => "coinset"
        output = Utils.popen_read("SHELL=bash #{bin}/coinset completion bash")
        (bash_completion/"coinset").write output
        output = Utils.popen_read("SHELL=zsh #{bin}/coinset completion zsh")
        (zsh_completion/"_coinset").write output
        prefix.install_metafiles
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/coinset-org/cli/releases/download/v1.0.1/coinset_Linux_arm64.tar.gz"
      sha256 "503ff1b82e8d72a3f4f976a32d2dce189ff0860cf9c61edafcba66a26ae90a90"

      def install
        bin.install "coinset" => "coinset"
        output = Utils.popen_read("SHELL=bash #{bin}/coinset completion bash")
        (bash_completion/"coinset").write output
        output = Utils.popen_read("SHELL=zsh #{bin}/coinset completion zsh")
        (zsh_completion/"_coinset").write output
        prefix.install_metafiles
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/coinset-org/cli/releases/download/v1.0.1/coinset_Linux_x86_64.tar.gz"
      sha256 "b3c4dd37008d4e1f849ba43af0da109625beb29008eb5fd58a586f7b888996ef"

      def install
        bin.install "coinset" => "coinset"
        output = Utils.popen_read("SHELL=bash #{bin}/coinset completion bash")
        (bash_completion/"coinset").write output
        output = Utils.popen_read("SHELL=zsh #{bin}/coinset completion zsh")
        (zsh_completion/"_coinset").write output
        prefix.install_metafiles
      end
    end
  end
end
