# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Coinset < Formula
  desc "CLI for accessing the Chia blockchain."
  homepage "https://www.coinset.org/"
  version "1.0.6"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/coinset-org/cli/releases/download/v1.0.6/coinset_Darwin_x86_64.tar.gz"
      sha256 "b7e619faf5867547ffa793a0818037878ddcb88318fb9ae0e871e689b23dbe2e"

      def install
        bin.install "coinset" => "coinset"
        output = Utils.popen_read("SHELL=bash #{bin}/coinset completion bash")
        (bash_completion/"coinset").write output
        output = Utils.popen_read("SHELL=zsh #{bin}/coinset completion zsh")
        (zsh_completion/"_coinset").write output
        prefix.install_metafiles
      end
    end
    on_arm do
      url "https://github.com/coinset-org/cli/releases/download/v1.0.6/coinset_Darwin_arm64.tar.gz"
      sha256 "9fac570e541eb2a8f0ac0b91950985303e008116e5fec5d17a6f707c13e71868"

      def install
        bin.install "coinset" => "coinset"
        output = Utils.popen_read("SHELL=bash #{bin}/coinset completion bash")
        (bash_completion/"coinset").write output
        output = Utils.popen_read("SHELL=zsh #{bin}/coinset completion zsh")
        (zsh_completion/"_coinset").write output
        prefix.install_metafiles
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/coinset-org/cli/releases/download/v1.0.6/coinset_Linux_x86_64.tar.gz"
        sha256 "cfba5b5909391a95013b776802217e9ca54da423d4bf80294b818006bc25ce3e"

        def install
          bin.install "coinset" => "coinset"
          output = Utils.popen_read("SHELL=bash #{bin}/coinset completion bash")
          (bash_completion/"coinset").write output
          output = Utils.popen_read("SHELL=zsh #{bin}/coinset completion zsh")
          (zsh_completion/"_coinset").write output
          prefix.install_metafiles
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/coinset-org/cli/releases/download/v1.0.6/coinset_Linux_arm64.tar.gz"
        sha256 "c9aea64d0337e65ba7f9568922bb38561ec557717230afb8c2b70487ca72640e"

        def install
          bin.install "coinset" => "coinset"
          output = Utils.popen_read("SHELL=bash #{bin}/coinset completion bash")
          (bash_completion/"coinset").write output
          output = Utils.popen_read("SHELL=zsh #{bin}/coinset completion zsh")
          (zsh_completion/"_coinset").write output
          prefix.install_metafiles
        end
      end
    end
  end
end
